### ISSUE TITLE
As a new user I want to create an account

### ISSUE THREAD

**Issue by DLzer** [golang-friends/slack-clone#1]
**Acceptance**

- Given a brand new user
- When creating a new account
- Then an account should be created in the repository

**Comment by incidrthreat** [comment]
@DLzer please see [AuthService-refactor branch](https://github.com/golang-friends/slack-clone/tree/AuthService-refactor).  If it fits the requirements we can close this issue.

**Comment by DLzer** [comment]
User story accepted.
As a brand new user I was able to create an account and have it store in the database. Awesome work!
