### ISSUE TITLE
Use go.mod to cache in Dockerfile

### ISSUE THREAD

**Issue by kkweon** [golang-friends/slack-clone#13]
This step was necessary to cache the dependency though.
Without it, everytime a code changes, everything has to be re downloaded and built.

For reference, https://medium.com/@petomalina/using-go-mod-download-to-speed-up-golang-docker-builds-707591336888

https://github.com/golang-friends/slack-clone/blob/34b30e60227459f746a5ca72d4d707b3bdda2a11/authservice/Dockerfile#L1-L11

**Comment by incidrthreat** [comment]
I'm impartial, either way works for me. Below are the stats that I pulled to ensure we had the quickest build overall.  You're right and assuming the dependencies don't change, the `go mod download` layer being cached will speed things up upon small code changes/rebuilds.  Times measured using Powershell `Measure-Command` cmdlet.  

| time |  |  | dependency changes |
|---|---|---|---|
| 25.82s | dockerfile with go mod dl | initial build |  |
| 23.96s | above dockerfile | initial build |  |
| 12.03s | dockerfile with go mod dl | rebuild code change | no |
| 21.54s | above dockerfile | rebuild code change | no |
| 28.65s | dockerfile with go mod dl | rebuild code change | yes |
| 21.45s | above dockerfile | rebuild code change | yes |
