### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by kkweon** [golang-friends/slack-clone#2]
how it structured is monolithic because of having root internal and root pkg. Each service will freely import each other causing tight coupling.

Do you have a suggestion or expectation on how the project should be structured? 

This is going to be a monorepo  

Each service should be a go module as its own without root go.mod

```
/auth
  /internal
  /...
  go.mod
/chat
  /internal
  /...
  go.mod
```

**Comment by incidrthreat** [comment]
I thought about this but ended up going with a monorepo setup.  This still keeps each service separate and allows for code sharing.  So something like this:
`project
├── cmd                     # contains microservices 
│   ├── '{microservice a}'  # "microservice a" project which contains "main" function to start app
│   │   └── main.go
│   └── '{microservice b}'  # "microservice b" project, also only contains "main" function to start app
│       └── main.go
├── docker                  # dockefile for each microservices
│   ├── '{microservice a}'
│   └── '{microservice b}'
├── internal                # internal package of each microservice. codes inside internal package only visible to its own microservice and cannot be shared
│   ├── '{microservice a}'
│   │   ├── rest            # HTTP entry point for REST API
│   │   ├── grpc            # gRPC entry
│   │   ├── repo            # repository / connector to database
│   │   └── service         # business logic layer which is handled by the microservice
│   └── '{microservice b}'
│       ├── rest
│       ├── grpc
│       ├── repo
│       └── service
├── pkg                     # public package directory which can be shared across project / microservices
│   └── models              # data model which usually 1:1 relation with database
│       ├── something.go
│       └── another.go
└── readme.md`

I am 100% open to suggestions.

**Comment by DLzer** [comment]
Both of these have perfect use cases. As a first team project mono-repo may be better suited to keep things organized. Otherwise I'd say we split each service into it's own repo.

**Comment by kkweon** [comment]
Ok, but I was not saying mono repo vs multiple repos. I assume the mono repo is agreed upon already.

if you do

```
cmd/
  serviceA/
  serviceB/
internal/
  serviceA/
  serviceB/
```

you can already see the codes are scattered compared to 

```
serviceA/
  cmd/
  internal/
serviceB/
  cmd/
  internal/
common/  
```

But, it's fine whichever. I just wanted to get aligned to ensure we are all on the same page.

**Comment by incidrthreat** [comment]
I'm not opposed to any of these structures as this is a learning/team project.

**Comment by incidrthreat** [comment]
Having read through quite a bit of documentation that discusses the pros/cons of Mono-repo vs Multi-Repo, I am inclined to agree with @kkweon.  I agree that each service should be standalone for coding groups and scalability.  If no one has any qualms or issues with this approach, I will refactor the code to reflect what was suggested:

```
serviceA/
  cmd/
  internal/
  Dockerfile
serviceB/
  cmd/
  internal/
  Dockerfile
common/
```

**Comment by DLzer** [comment]
Sounds good! If you'd like I have a PR out for structural updates with Domain/Service splitting ( #3 ) Feel free to utilize that branch.

**Comment by incidrthreat** [comment]
> 
> Sounds good! If you'd like I have a PR out for structural updates with Domain/Service splitting ( #3 ) Feel free to utilize that branch.

@DLzer, I had a look at the PR and it looks like it just shuffles the protos into a different folder.  I'm gonna push anything auth service related into a single service folder.  Probably rename a few things to line up.  Additonally, I will also be putting in a test case for one of the funcs so folks can get an idea on how to build the test cases out and then leave it for others to contribute.  I'll throw some comments on your test case PR as well.
