### ISSUE TITLE
Let's avoid case sensitive names

### ISSUE THREAD

**Issue by kkweon** [golang-friends/slack-clone#8]
Let's rename `AuthService` to `authservice` or simply `auth` (lowercase) to be consistent?

> **AuthService**/cmd/authservice/authservice.go -> **auth**/cmd/authservice/authservice.go

Not all file systems are case sensitive by default.

**Comment by incidrthreat** [comment]
Fixed in [313e6f2](https://github.com/golang-friends/slack-clone/commit/313e6f2fb99ee231df861c90a134f7353ef2b218).
